"""Add created_at and deleted_at to Feedback

Revision ID: dfb7a6a68358
Revises: 124531b9d2eb
Create Date: 2024-06-08 19:01:06.148389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb7a6a68358'
down_revision = '124531b9d2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('feedback', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'deleted_at')
    op.drop_column('feedback', 'created_at')
    # ### end Alembic commands ###
